// Static reference content for the Culinary Basics page. Not pulled from
// any API — written once, hardcoded, and paired with a verified YouTube
// tutorial per skill (see the `youtube` field; filled in after manual
// verification that each link is real and on-topic).

export const CULINARY_CATEGORIES = [
  {
    id: "knife-skills",
    title: "Knife Skills",
    skills: [
      {
        id: "hold-a-knife",
        title: "How to Hold a Knife",
        steps: [
          "Grip the blade itself, not just the handle: pinch the blade between your thumb and the side of your index finger, right where it meets the handle.",
          "Wrap your remaining three fingers around the handle.",
          "On your guiding hand, curl your fingertips under and rest your knuckles against the flat of the blade — the blade rides against your knuckles as a guide, fingertips never exposed.",
          "Move the knife in a smooth, rocking motion for most cuts, letting the tip stay mostly in contact with the board.",
        ],
        tip: "The 'pinch grip' feels awkward for the first week and then becomes automatic — it gives you far more control than gripping the handle like a hammer, and it's the single biggest lever for cutting safely and consistently.",
        youtube: { url: "https://www.youtube.com/watch?v=RkFwq_JNt8A", title: "Learn Basic Kitchen Knife Skills: How to use a chef knife", channel: "ZWILLING USA" },
      },
      {
        id: "basic-dice",
        title: "The Basic Dice",
        steps: [
          "Square off your ingredient first (e.g. trim an onion or potato flat) so it sits stably on the board.",
          "Slice the item into even planks of your target thickness.",
          "Stack or line up the planks and cut into even strips (batons) of the same width.",
          "Turn the strips 90° and cut crosswise into cubes — small dice is about 1/4\", medium dice about 1/2\", large dice about 3/4\".",
        ],
        tip: "Consistency matters more than size: uneven pieces cook unevenly, so aim for every cube to match its neighbors rather than hitting an exact measurement.",
        youtube: { url: "https://www.youtube.com/watch?v=VJNA4vrdWec", title: "How to Master Basic Knife Skills - Knife Cuts 101", channel: "Chef Billy Parisi" },
      },
      {
        id: "julienne",
        title: "Julienne Cut",
        steps: [
          "Trim your vegetable into a rectangular block, squaring off the rounded sides.",
          "Slice the block lengthwise into thin planks, about 1/8\" thick.",
          "Stack a few planks at a time and cut lengthwise into thin matchsticks, about 1/8\" x 1/8\" x 2\"-3\" long.",
        ],
        tip: "This is the cut behind stir-fry vegetables and garnishes — thin enough to cook fast and evenly, and uniform enough to look intentional on a plate.",
        youtube: { url: "https://www.youtube.com/watch?v=S6D2FbNymF8", title: "How to Julienne Vegetables like Carrots, Peppers, and Zucchini | Knife Skills 101", channel: "ZWILLING" },
      },
      {
        id: "brunoise",
        title: "Brunoise Cut",
        steps: [
          "Start with a julienne cut (thin matchsticks, about 1/8\" thick).",
          "Line up the matchsticks and cut crosswise at 1/8\" intervals to produce tiny, even cubes.",
        ],
        tip: "Brunoise is essentially 'julienne, then dice' — get comfortable with julienne first and brunoise is just one more pass with the knife.",
        youtube: { url: "https://www.youtube.com/watch?v=wyzq620fRvk", title: "Knife Skills - How To Brunoise", channel: "ZWILLING" },
      },
      {
        id: "chiffonade",
        title: "Chiffonade Cut",
        steps: [
          "Stack leafy herbs or greens (basil, mint, sage) flat, largest leaves on the bottom.",
          "Roll the stack tightly into a cigar shape.",
          "Slice crosswise into thin ribbons using a smooth, single-motion cut rather than a sawing motion.",
        ],
        tip: "Sawing back and forth bruises delicate leaves and turns them black at the edges — use one clean slicing motion per cut for bright green ribbons.",
        youtube: { url: "https://www.youtube.com/watch?v=ShbcEabd17E", title: "How to Chiffonade or Cut Basil", channel: "Epicurious" },
      },
      {
        id: "batonnet-tourne",
        title: "Batonnet & Tourné Cuts",
        steps: [
          "Batonnet: square off your vegetable, slice into planks about 1/4\" thick, then cut those planks into sticks about 1/4\" x 1/4\" x 2\"-3\" — think 'steak fry' size.",
          "Tourné: peel a small, firm vegetable (potato, carrot) and cut it into a small football/barrel shape with 5-7 flat faces, using short curved strokes from the top and bottom toward the widest point.",
          "Rotate the piece in your guiding hand as you cut each face so the facets stay even.",
        ],
        tip: "Tourné is a classic culinary-school drill more about knife control than everyday necessity — most home cooks will use batonnet far more often (it's the basis for hand-cut fries).",
        youtube: null,
      },
    ],
  },
  {
    id: "cutting-ingredients",
    title: "Cutting Specific Ingredients",
    skills: [
      {
        id: "cut-onion",
        title: "How to Cut an Onion",
        steps: [
          "Slice the onion in half through the root end, then peel off the skin.",
          "Place one half flat-side down, root facing away from you, and make several horizontal cuts toward (not through) the root, keeping it intact as a hinge.",
          "Make vertical cuts from the top down toward the root, again leaving the root uncut.",
          "Turn the onion and slice crosswise from the tip toward the root — it will fall apart into even dice, held together the whole time by the root end.",
        ],
        tip: "Keeping the root intact until the very last cut is what makes this fast and safe — it holds the layers together so your guiding hand always has something stable to grip.",
        youtube: { url: "https://www.youtube.com/watch?v=hUiLqi479TE", title: "7 Ways To Cut Onions Like A Pro Chef", channel: "Bon Appétit" },
      },
      {
        id: "mince-garlic",
        title: "How to Mince Garlic",
        steps: [
          "Smash the clove with the flat side of your knife to loosen and split the papery skin, then peel it off.",
          "Trim off the tough root end.",
          "Slice the clove thinly, then rock the knife tip over the pile repeatedly, gathering the garlic back into a pile between passes, until it's finely minced.",
        ],
        tip: "A light sprinkle of salt on the garlic while mincing helps break it down into a near-paste and keeps the pieces from sticking to the blade.",
        youtube: { url: "https://www.youtube.com/watch?v=2Yt6pKLU_10", title: "Cooking School: How To Mince Garlic... Fast", channel: "America's Test Kitchen" },
      },
      {
        id: "tomato-concasse",
        title: "Tomato Concassé",
        steps: [
          "Cut a shallow X into the base of each tomato and drop into boiling water for 20-30 seconds.",
          "Transfer immediately to an ice bath to stop the cooking.",
          "The skin will peel off easily by hand starting at the X.",
          "Halve the tomato, squeeze or scoop out the seeds and core, then dice the remaining flesh.",
        ],
        tip: "This blanch-and-shock method is the standard way to get skinless, seedless tomato for sauces and garnishes without turning the flesh mushy.",
        youtube: { url: "https://www.youtube.com/watch?v=AwrJiUod5Tw", title: "How to peel and seed fresh tomatoes - A crucial technique for the perfect tomato sauce!", channel: "Food & Style" },
      },
      {
        id: "cut-bell-pepper",
        title: "How to Cut a Bell Pepper",
        steps: [
          "Stand the pepper up and slice straight down along each of its natural flat sides, working around the stem and core.",
          "You'll end up with 3-4 flat lobes plus the stem/core/seed cluster to discard.",
          "Lay each lobe skin-side down and trim any remaining white pith.",
          "Slice or dice each flat lobe as needed — it's now easy to cut evenly since it lies flat.",
        ],
        tip: "Cutting around the core instead of chopping straight through it means you never have to dig loose seeds out of your dice afterward.",
        youtube: { url: "https://www.youtube.com/watch?v=ElzxfEcYiv8", title: "How to Deseed, Cut, Julienne and Dice a Bell Pepper (Step-by-Step Tutorial)", channel: "Chef Abbie Gellman" },
      },
      {
        id: "fillet-round-fish",
        title: "How to Fillet a Round Fish",
        steps: [
          "Scale the fish if needed, then make a cut behind the gills down to the spine.",
          "Turn the knife flat and, starting from that cut, run the blade along one side of the backbone toward the tail, following the bones closely.",
          "Lift the fillet away as you cut, keeping the blade angled toward the bones to leave as little flesh behind as possible.",
          "Flip the fish and repeat on the other side.",
          "Lay each fillet skin-side down and slide the knife between skin and flesh to remove the skin, and run your fingers over the flesh to find and pull any remaining pin bones with tweezers.",
        ],
        tip: "Let the knife do the work by following the bones rather than forcing straight lines — a flexible fillet knife makes this dramatically easier than a rigid chef's knife.",
        youtube: { url: "https://www.youtube.com/watch?v=OKsl4qCHVMc", title: "How to Fillet a Round Fish", channel: "Auguste Escoffier School of Culinary Arts" },
      },
      {
        id: "break-down-chicken",
        title: "How to Break Down a Whole Chicken",
        steps: [
          "Remove the legs first: cut through the skin between leg and body, then pop the thigh bone out of its hip socket and cut through the joint.",
          "Separate drumstick from thigh by cutting through the connecting joint (you can find it by feel/bending).",
          "Remove the wings by cutting through the shoulder joint where wing meets breast.",
          "Cut along either side of the backbone to remove it, then split the remaining breast in half through the breastbone, or cut each breast off the bone entirely.",
        ],
        tip: "Cut through joints and cartilage, not bone — if you're sawing hard against something solid, you're probably not lined up on the joint; feel around a bit and reposition.",
        youtube: { url: "https://www.youtube.com/watch?v=oQbZCLvfpIw", title: "How to Break Down a Whole Chicken", channel: "Made In Cookware" },
      },
      {
        id: "trim-meat",
        title: "Trimming Meat (Silverskin & Fat Cap)",
        steps: [
          "Identify silverskin — the thin, pearly, tough membrane on cuts like tenderloin — and slide the knife tip just underneath it at one end.",
          "Angle the blade slightly upward (away from the meat) and slice along its length in long strokes, pulling the silverskin taut with your other hand as you go.",
          "For a fat cap, trim it down to a thin, even layer (rather than removing entirely) unless the recipe calls for full removal — this protects the meat and renders during cooking.",
        ],
        tip: "Silverskin doesn't break down with cooking the way fat does — leaving it on results in a chewy, rubbery bite, so it's always worth removing before cooking.",
        youtube: { url: "https://www.youtube.com/watch?v=kchBGaIoxJ0", title: "How to Trim Silver Skin", channel: "Martha Stewart" },
      },
      {
        id: "devein-shrimp-shuck-oysters",
        title: "Deveining Shrimp & Shucking Oysters",
        steps: [
          "To devein: peel the shrimp, then run a paring knife shallowly along the curved back to expose the dark vein, and lift it out with the knife tip or your fingers.",
          "To shuck an oyster: hold it flat-side up in a folded towel, insert an oyster knife into the hinge at the pointed end, and twist firmly to pop the hinge.",
          "Slide the knife along the inside of the top shell to sever the adductor muscle, then remove the top shell.",
          "Slide the knife under the oyster to detach it from the bottom shell without spilling its liquor.",
        ],
        tip: "For oysters, always use a stab-resistant glove or thick towel on your holding hand — oyster knives are blunt but the shells are sharp and slippery, and slips are the most common kitchen injury with this task.",
        youtube: null,
      },
    ],
  },
  {
    id: "knife-care",
    title: "Knife Care",
    skills: [
      {
        id: "honing-vs-sharpening",
        title: "Honing vs. Sharpening",
        steps: [
          "Honing realigns a blade's edge that has micro-bent out of true from normal use — it doesn't remove metal, just straightens what's already there.",
          "Sharpening actually grinds away metal on a stone to create a new, fresh edge — it's what fixes a blade that's genuinely dull.",
          "Hone before most cooking sessions (takes seconds); sharpen every few weeks to months depending on use.",
        ],
        tip: "If your knife still feels dull immediately after honing, it needs sharpening, not more honing — honing can't fix an edge that's actually worn away.",
        youtube: { url: "https://www.youtube.com/watch?v=yaPC1Db1M3M", title: "Knife Honing vs. Sharpening: How Much Difference Does It Make?", channel: "Work Sharp Tools" },
      },
      {
        id: "whetstone-sharpening",
        title: "Sharpening on a Whetstone",
        steps: [
          "Soak a water stone as directed (some need 10-15 minutes; oil stones don't need soaking).",
          "Hold the blade against the stone at roughly a 15-20° angle and keep that angle consistent throughout.",
          "Starting at the heel, draw the blade across the stone in a sweeping motion so the entire edge contacts the stone, moving toward the tip.",
          "Repeat for a set number of strokes, then flip and repeat evenly on the other side.",
          "Finish on a finer-grit stone if you have one, then strop or hone to clean up the edge.",
        ],
        tip: "Consistency of angle matters far more than pressure — press lightly and focus on keeping the same angle stroke after stroke rather than pushing hard.",
        youtube: { url: "https://www.youtube.com/watch?v=AFbjn0aUZAU", title: "How to Sharpen a Knife on a Whetstone", channel: "Serious Eats (Kenji López-Alt)" },
      },
      {
        id: "honing-steel",
        title: "Using a Honing Steel",
        steps: [
          "Hold the steel vertically, tip resting on a towel on the counter for stability, or hold it out horizontally away from your body.",
          "Set the blade against the steel at about a 15-20° angle near the handle end of the steel.",
          "Draw the knife down and across in a smooth arc so the entire edge passes over the steel, from heel to tip.",
          "Repeat on the other side of the blade, alternating sides for 3-5 passes each.",
        ],
        tip: "Let the weight of the knife do the work — you're realigning the edge, not scrubbing it, so a light touch is all that's needed.",
        youtube: { url: "https://www.youtube.com/watch?v=Rrd1YYynJoA", title: "How To Sharpen a Knife With A Honing Steel", channel: "Made In Cookware" },
      },
      {
        id: "knife-maintenance",
        title: "Basic Knife Maintenance & Storage",
        steps: [
          "Hand wash and dry knives immediately after use — never leave them soaking or run them through a dishwasher.",
          "Store in a knife block, on a magnetic strip, or with blade guards — never loose in a drawer where the edge can chip against other utensils.",
          "Cut on wood or plastic boards, never glass, stone, or ceramic, which will dull an edge almost instantly.",
          "Hone regularly and sharpen periodically as part of routine use, not just when the knife feels obviously dull.",
        ],
        tip: "Most 'this knife is bad' complaints are actually 'this knife hasn't been maintained' — a mid-range knife kept sharp will outperform an expensive one left to dull.",
        youtube: { url: "https://www.youtube.com/watch?v=t-_qzsMF8RM", title: "The Best Way To Sharpen & Clean Knives (And The Worst)", channel: "Epicurious" },
      },
    ],
  },
  {
    id: "kitchen-fundamentals",
    title: "Kitchen Fundamentals & Food Safety",
    skills: [
      {
        id: "mise-en-place",
        title: "Mise en Place",
        steps: [
          "Read the full recipe once, start to finish, before touching anything.",
          "Wash, peel, and cut every ingredient the recipe calls for, and measure out liquids/spices into small bowls or containers.",
          "Arrange everything in the order you'll use it, near your cooking station.",
          "Clean as you go so your workspace stays usable throughout.",
        ],
        tip: "\"Mise en place\" literally means 'everything in its place' — doing this before you turn on the heat is what separates a calm cook from a frantic one, especially for anything with fast-moving steps.",
        youtube: { url: "https://www.youtube.com/watch?v=tkvAhaAC0ms", title: "Become a Mise en Place Pro with Mini Prep Bowls", channel: "America's Test Kitchen" },
      },
      {
        id: "food-safety-basics",
        title: "Food Safety Basics",
        steps: [
          "Keep perishable food out of the 'danger zone' (40°F-140°F / 4°C-60°C) for more than 2 hours total.",
          "Use separate cutting boards (or wash thoroughly between uses) for raw meat versus produce to avoid cross-contamination.",
          "Wash hands before cooking and after handling raw meat, poultry, or eggs.",
          "Refrigerate leftovers within 2 hours of cooking, and reheat to at least 165°F (74°C) before eating.",
        ],
        tip: "Bacteria grow fastest in the danger zone, not at extreme heat or cold — the goal is minimizing time spent in that middle range, from grocery trip to fridge to plate.",
        youtube: { url: "https://www.youtube.com/watch?v=o7LFGJ_ngw0", title: "ServSafe Chapter 4: The Flow of Food", channel: "Wekiva Culinary" },
      },
      {
        id: "reading-scaling-recipe",
        title: "Reading & Scaling a Recipe",
        steps: [
          "Read the entire recipe once before starting, noting total time, equipment, and any steps that need advance prep (marinating, chilling dough, etc.).",
          "To scale, multiply every ingredient by the same ratio (target servings ÷ original servings).",
          "Be aware that leavening agents, spices, and salt don't always scale perfectly linearly — start slightly conservative and adjust to taste at large scale changes.",
          "Cooking times often don't scale linearly either (a doubled roast won't cook in exactly double the time) — rely on temperature/doneness cues over the clock when scaling up.",
        ],
        tip: "The most common recipe failure is skipping the initial read-through — hidden steps like 'chill for 2 hours' or 'let rest overnight' are easy to miss if you start cooking before reading to the end.",
        youtube: { url: "https://www.youtube.com/watch?v=Q2tkryZa9VA", title: "How to Read a Recipe", channel: "Spoons Across America" },
      },
      {
        id: "kitchen-math",
        title: "Basic Kitchen Math & Yields",
        steps: [
          "Know the core volume conversions: 3 tsp = 1 tbsp, 16 tbsp = 1 cup, 2 cups = 1 pint, 4 cups = 1 quart.",
          "Know common weight-to-volume approximations for baking staples (e.g. 1 cup all-purpose flour ≈ 120g) since volume measurements of dry goods vary by how they're packed.",
          "Account for trim/yield loss when a recipe calls for 'prepared' weight — a whole onion or a bone-in chicken breast weighs more than the edible portion you'll actually use.",
          "Use a kitchen scale for baking and for scaling recipes accurately — it removes the packing-density guesswork that measuring cups introduce.",
        ],
        tip: "Weight is more reliable than volume for anything that compacts (flour, brown sugar, shredded cheese) — two cooks scooping 'a cup of flour' can genuinely end up with different amounts.",
        youtube: { url: "https://www.youtube.com/watch?v=bdT-dKeO3wI", title: "Measurements 101. A Chef's Beginner Guide To Basic Measurements and Conversions!", channel: "Kitchen Conquest" },
      },
      {
        id: "knife-kitchen-safety",
        title: "Knife & Kitchen Safety Habits",
        steps: [
          "Always cut on a stable board — place a damp towel underneath to stop it from sliding.",
          "Curl your guiding-hand fingertips under (claw grip) so knuckles, not fingertips, face the blade.",
          "Never try to catch a falling knife — step back and let it drop.",
          "Keep knives sharp: a dull blade needs more force and is more likely to slip.",
          "Announce yourself ('behind,' 'sharp,' 'hot') when moving around others in a shared kitchen space.",
        ],
        tip: "Most kitchen cuts happen with dull knives, not sharp ones — a sharp blade behaves predictably and needs less force, which is safer even though it sounds counterintuitive.",
        youtube: { url: "https://www.youtube.com/watch?v=VIm0pb-Mag0", title: "How To Use a Knife", channel: "America's Test Kitchen" },
      },
    ],
  },
  {
    id: "seasoning-flavor",
    title: "Seasoning & Flavor Building",
    skills: [
      {
        id: "seasoning-in-layers",
        title: "Seasoning in Layers",
        steps: [
          "Season each major stage of a dish, not just at the end — the onions as they sweat, the meat before it sears, the sauce as it reduces.",
          "Use a light hand at each stage; you can always add more, but you can't take salt back out.",
          "Different salts and seasonings behave differently — salt added early has time to penetrate and dissolve, while a finishing salt added at the end stays as a textural pop.",
        ],
        tip: "A dish seasoned only at the very end often tastes 'salty but flat' — layering seasoning throughout builds a rounder, more integrated flavor than one big addition at the finish.",
        youtube: { url: "https://www.youtube.com/watch?v=rEao0BS4HQo", title: "How To Salt Like a PRO!", channel: "Chef Jean-Pierre" },
      },
      {
        id: "tasting-adjusting",
        title: "Tasting & Adjusting as You Cook",
        steps: [
          "Taste at every major stage — after building a base, after adding liquid, and right before serving.",
          "Use a clean spoon each time (never the one that's been in your mouth) to avoid contaminating the pot.",
          "When something tastes flat, consider what's actually missing: usually salt, acid (lemon/vinegar), fat, or heat/spice — not necessarily 'more of everything.'",
          "Make small adjustments and re-taste rather than dumping in a large correction at once.",
        ],
        tip: "\"Tastes flat\" is almost always fixed by acid or salt, not more of the main seasoning — a squeeze of lemon can fix a dish that's been over-salted-tasting for the wrong reason.",
        youtube: { url: "https://www.youtube.com/watch?v=SGY2kdomvS8", title: "How to Season Your Food to Taste", channel: "Blue Apron" },
      },
      {
        id: "aromatics-base",
        title: "Aromatics: Mirepoix, Sofrito & the Holy Trinity",
        steps: [
          "Mirepoix (French): diced onion, carrot, celery, roughly 2:1:1 by weight — the base for most French stocks, soups, and braises.",
          "Sofrito (varies by region, Spanish/Latin/Italian roots): typically onion, garlic, tomato, and peppers, cooked down slowly into a flavor paste.",
          "Holy Trinity (Cajun/Creole): onion, celery, and bell pepper in roughly equal parts, replacing carrot with bell pepper.",
          "In all cases, sweat the vegetables slowly in fat over low-medium heat until soft and fragrant, without browning, to build the base before adding the main ingredients.",
        ],
        tip: "These bases exist because onion + one or two other aromatics, cooked low and slow, dissolve into a dish and build savory depth without anyone tasting 'onion' specifically — it's structural flavor, not a topping.",
        youtube: { url: "https://www.youtube.com/watch?v=DEusufRe3lE", title: "Aromatics 101 | The Classic Mirepoix", channel: "Mastering the Techniques of Cooking" },
      },
      {
        id: "deglazing",
        title: "Deglazing a Pan",
        steps: [
          "After searing meat or vegetables, remove them from the pan and pour off excess fat, leaving the browned bits (fond) stuck to the bottom.",
          "Add a splash of liquid (wine, stock, even water) to the hot pan.",
          "Scrape the bottom firmly with a wooden spoon or spatula as the liquid bubbles, lifting the fond into the liquid.",
          "Let the liquid reduce slightly — this is now the base for a pan sauce.",
        ],
        tip: "That browned, stuck-on layer (fond) is concentrated flavor, not something to scrub away before making a sauce — deglazing is how you get it back.",
        youtube: { url: "https://www.youtube.com/watch?v=Ze7LyJVhexE", title: "The perfect easy chicken recipe to tackle your first French pan sauce", channel: "French Cooking Academy" },
      },
    ],
  },
  {
    id: "dry-heat",
    title: "Cooking Methods: Dry Heat",
    skills: [
      {
        id: "sauteing",
        title: "Sautéing",
        steps: [
          "Heat a small amount of fat in a wide pan over medium-high heat until shimmering.",
          "Add food in a single layer without crowding the pan — crowding traps steam and stops browning.",
          "Keep the food moving with tossing or stirring for quick, even cooking.",
          "Work in batches if needed rather than overloading the pan.",
        ],
        tip: "A crowded pan steams instead of sautés — if food is releasing a lot of liquid and not browning, it's too full; cook in batches.",
        youtube: { url: "https://www.youtube.com/watch?v=mROtdl6BDdM", title: "Sauté Like a Chef: Essential Cooking Skills", channel: "Providence Community Teaching Kitchen" },
      },
      {
        id: "pan-searing",
        title: "Pan-Searing",
        steps: [
          "Pat the food (usually meat) completely dry — moisture on the surface prevents browning.",
          "Heat a heavy pan (cast iron or stainless works well) until very hot, then add a high-smoke-point oil.",
          "Lay the food away from you into the pan and leave it undisturbed until it releases easily and has a deep brown crust.",
          "Flip once, sear the other side, then finish to temperature (in the pan, oven, or by resting).",
        ],
        tip: "If meat is sticking stubbornly, it usually isn't ready to flip yet — a proper sear naturally releases from the pan when the crust has formed.",
        youtube: { url: "https://www.youtube.com/watch?v=lVcTvHTn6Dw", title: "How to Cook the Perfect Steak", channel: "Chef Jean-Pierre" },
      },
      {
        id: "roasting",
        title: "Roasting",
        steps: [
          "Preheat the oven fully before adding food — a cold or half-heated oven changes cook times unpredictably.",
          "Use a rack or elevate the food when possible so hot air circulates on all sides.",
          "Avoid overcrowding the pan, which traps steam and prevents browning, same as sautéing.",
          "Use a thermometer for meats and check for doneness cues (fork-tender, golden color) rather than relying on time alone.",
        ],
        tip: "Roasting is really just 'oven-baking with the goal of browning' — dry, circulating heat, not a covered or steamy environment.",
        youtube: { url: "https://www.youtube.com/watch?v=OvQ-NOR5bQE", title: "Easy One-Pan Dinner: Cast Iron Roasted Chicken and Root Vegetables", channel: "America's Test Kitchen" },
      },
      {
        id: "grilling",
        title: "Grilling",
        steps: [
          "Preheat the grill and clean/oil the grates to prevent sticking.",
          "Set up two heat zones (direct high heat and indirect lower heat) so you can sear and then move food to finish gently.",
          "Sear over direct heat for color and char, then move to indirect heat to finish cooking through without burning.",
          "Let food rest briefly off the grill before cutting, same as any seared protein.",
        ],
        tip: "Constantly flipping and moving food is usually a sign of an under-confident cook, not a technique — let each side develop real color before you touch it.",
        youtube: { url: "https://www.youtube.com/watch?v=yPAeRiKa0h8", title: "Grilling 101", channel: "Rick Bayless" },
      },
      {
        id: "broiling",
        title: "Broiling",
        steps: [
          "Position an oven rack close to the broiler element and preheat the broiler.",
          "Place food on a broiler-safe pan; a little distance from the heat source is still needed even though it's close-range.",
          "Watch constantly — broiling browns food very fast and can go from perfect to burnt in under a minute.",
          "Flip if needed for even browning on both sides, since heat is coming from one direction only.",
        ],
        tip: "Think of broiling as 'upside-down grilling' — intense, direct, one-directional heat that needs your full attention the entire time it's on.",
        youtube: { url: "https://www.youtube.com/watch?v=rSHPkVZ0sFA", title: "How to Broil", channel: "Allrecipes" },
      },
      {
        id: "deep-frying",
        title: "Deep-Frying",
        steps: [
          "Use an oil with a high smoke point (vegetable, canola, peanut) and heat to the target temperature, usually 325-375°F (163-190°C), using a thermometer.",
          "Pat food dry and, if breading, coat just before frying rather than letting it sit.",
          "Lower food in gently and fry in small batches to avoid dropping the oil temperature.",
          "Drain on a wire rack (not paper towels alone) so steam escapes and the coating stays crisp.",
        ],
        tip: "Overcrowding the fryer drops the oil temperature fast, which is exactly what causes greasy, soggy results — fry in smaller batches and let the oil recover between them.",
        youtube: { url: "https://www.youtube.com/watch?v=ypAvbooptK4", title: "Swimming in Hot Oil–No Fear Frying", channel: "America's Test Kitchen" },
      },
    ],
  },
  {
    id: "moist-heat",
    title: "Cooking Methods: Moist Heat & Combination",
    skills: [
      {
        id: "braising",
        title: "Braising",
        steps: [
          "Sear the main ingredient (usually a tougher cut of meat) on all sides for color and flavor first.",
          "Add aromatics and enough liquid to come partway up the food (not fully submerged).",
          "Cover and cook low and slow — oven or stovetop — until fork-tender; this can take hours for tough cuts.",
          "Optionally reduce the braising liquid afterward into a sauce.",
        ],
        tip: "Braising is built for tough, connective-tissue-rich cuts — low, moist, prolonged heat is what melts collagen into gelatin, which is why a quick sear alone would leave the same cut chewy.",
        youtube: { url: "https://www.youtube.com/watch?v=b6Yqw6J8WHo", title: "How To Make Beef Bourguignon", channel: "Chef Jean-Pierre" },
      },
      {
        id: "poaching",
        title: "Poaching",
        steps: [
          "Bring a flavorful liquid (stock, wine, water with aromatics) to a bare simmer — small, lazy bubbles, not a rolling boil.",
          "Submerge the food gently in the liquid.",
          "Cook gently until just done, watching closely since poaching is meant to be delicate.",
          "Remove with a slotted spoon so the food doesn't overcook while sitting in hot liquid.",
        ],
        tip: "A rolling boil is too aggressive for poaching and will toughen delicate proteins like fish or eggs — the liquid should barely move.",
        youtube: { url: "https://www.youtube.com/watch?v=NDYPzJWoaKk", title: "Butter Poached Salmon", channel: "Chef Jean-Pierre" },
      },
      {
        id: "steaming",
        title: "Steaming",
        steps: [
          "Bring a small amount of water to a boil in a covered pot fitted with a steamer basket or insert, keeping the food above (not touching) the water.",
          "Add food, cover, and let steam circulate and cook it without direct contact with the liquid.",
          "Check periodically, since steam builds heat quickly once you lift the lid to peek.",
        ],
        tip: "Steaming preserves color, texture, and nutrients better than boiling because the food never sits in water that can leach flavor and nutrients out.",
        youtube: { url: "https://www.youtube.com/watch?v=MPDg2eF0Rxs", title: "Why Steaming Is The Most Underrated Cooking Technique", channel: "Epicurious" },
      },
      {
        id: "blanching-shocking",
        title: "Blanching & Shocking",
        steps: [
          "Drop vegetables into a large pot of well-salted, rapidly boiling water for a short time (seconds to a couple of minutes depending on the item).",
          "Immediately transfer to a bowl of ice water (the 'shock') to stop the cooking instantly.",
          "Drain well once fully cooled.",
        ],
        tip: "The ice bath is not optional — without shocking, residual heat keeps cooking the vegetable after it leaves the pot, turning bright green beans dull olive in a couple of minutes.",
        youtube: { url: "https://www.youtube.com/watch?v=RkkVBt8b7P4", title: "Why Professional Chefs ALWAYS Blanch Their Vegetables First, and How?", channel: "Taste of Asian Food" },
      },
      {
        id: "stewing",
        title: "Stewing",
        steps: [
          "Cut the main ingredient into smaller, uniform pieces (unlike braising, which often uses larger cuts).",
          "Sear if desired, then fully submerge in liquid along with aromatics and vegetables.",
          "Simmer gently, covered or uncovered, until everything is tender — the liquid itself becomes part of the finished dish.",
        ],
        tip: "The main difference from braising is proportion: stewing fully submerges smaller pieces in liquid that's meant to be eaten as part of the dish, while braising partially submerges larger pieces.",
        youtube: { url: "https://www.youtube.com/watch?v=mAdX2PDeWnk", title: "Andy Makes Chicken and Tomato Stew", channel: "Bon Appétit" },
      },
    ],
  },
  {
    id: "stocks-sauces",
    title: "Stocks, Soups & Sauces",
    skills: [
      {
        id: "basic-stock",
        title: "Making a Basic Stock",
        steps: [
          "Combine bones (for meat stock) or vegetable scraps with cold water in a large pot — starting with cold water helps extract flavor gradually and keeps the stock clear.",
          "Bring to a bare simmer, never a boil, and skim off foam and impurities that rise to the top.",
          "Add aromatics (mirepoix, herbs, peppercorns) partway through so they don't overcook.",
          "Simmer uncovered for hours (longer for beef/veal bones, shorter for chicken or vegetables), then strain through a fine sieve.",
        ],
        tip: "A rolling boil emulsifies fat and impurities into the liquid, producing a cloudy, greasy stock — a bare simmer is what keeps it clean and clear.",
        youtube: { url: "https://www.youtube.com/watch?v=XlDR761JSX8", title: "How to Make Roasted Chicken Stock", channel: "Chef Jean-Pierre" },
      },
      {
        id: "clarifying-consomme",
        title: "Clarifying a Consommé",
        steps: [
          "Mix cold stock with a 'raft' mixture of egg whites, ground lean meat, and finely diced aromatics.",
          "Heat slowly while stirring, then stop stirring once the raft begins to form and float — it will trap impurities as it rises.",
          "Let it simmer very gently undisturbed, with a small hole in the raft for the liquid to bubble through.",
          "Ladle the clear liquid out from beneath the raft (or strain gently through cheesecloth) without breaking it apart.",
        ],
        tip: "The egg whites coagulate and physically trap cloudy particles as they rise through the liquid — disturbing or stirring the raft once it's formed will break it apart and cloud the consommé right back up.",
        youtube: { url: "https://www.youtube.com/watch?v=YBZXdQwQEfA", title: "How to make: Consommé (Chicken)", channel: "Adam Byatt" },
      },
      {
        id: "making-a-roux",
        title: "Making a Roux",
        steps: [
          "Melt equal parts fat (usually butter) and flour together by weight in a pan over medium heat.",
          "Whisk continuously to combine into a smooth paste.",
          "Cook further for a darker roux: white roux (a couple minutes, for cream sauces), blond roux (a few more minutes, pale gold), brown roux (10+ minutes, nutty and deep, for gumbo).",
          "Whisk the roux into a warm liquid gradually (or the liquid into the roux) to avoid lumps, then simmer to thicken.",
        ],
        tip: "The darker a roux gets, the less thickening power it has but the more flavor it adds — that's the trade-off between a béchamel (white, mostly for body) and a gumbo roux (dark, mostly for flavor).",
        youtube: { url: "https://www.youtube.com/watch?v=ZkW6xEMYlRE", title: "How to Make A Roux, 4 types", channel: "Allrecipes AU | NZ" },
      },
      {
        id: "mother-sauces",
        title: "The Five Mother Sauces",
        steps: [
          "Béchamel: milk thickened with a white roux — the base for cream sauces and gratins.",
          "Velouté: white stock (chicken, veal, or fish) thickened with a blond roux.",
          "Espagnole: brown stock thickened with a brown roux, plus tomato and aromatics — the base for demi-glace.",
          "Tomato Sauce: tomatoes cooked down, sometimes with a roux, into a base sauce.",
          "Hollandaise: egg yolks and butter emulsified with acid — the odd one out, thickened by emulsification rather than a roux.",
        ],
        tip: "These five are called 'mother' sauces because dozens of familiar sauces are just one of them plus a couple of extra ingredients — a mornay is béchamel plus cheese, for example.",
        youtube: { url: "https://www.youtube.com/watch?v=xniS7kMpW4I", title: "The 5 Sauces Every Chef Needs to Learn", channel: "Fallow" },
      },
      {
        id: "pan-sauce",
        title: "Making a Pan Sauce",
        steps: [
          "After searing meat, remove it and pour off excess fat, keeping the fond in the pan.",
          "Deglaze with wine, stock, or another liquid, scraping up the browned bits.",
          "Reduce the liquid by simmering until it thickens slightly.",
          "Finish by whisking in cold butter off the heat (monter au beurre) for shine and body, and adjust seasoning.",
        ],
        tip: "Finishing with cold butter off the heat, not on it, is what gives a pan sauce its glossy, silky texture — adding it while still boiling can break the emulsion and turn it greasy.",
        youtube: { url: "https://www.youtube.com/watch?v=TtbhCXC0KA4", title: "How To Make a Pan Sauce Using Fond and A Stainless Steel Pan", channel: "Tom's Kitchen" },
      },
      {
        id: "vinaigrette-emulsification",
        title: "Vinaigrette & Emulsification",
        steps: [
          "Start with an acid (vinegar or citrus) and any flavorings (mustard, shallot, salt) in a bowl.",
          "Whisk continuously while adding oil in a slow, thin stream — this is what breaks the oil into tiny droplets suspended in the acid.",
          "Keep whisking until the mixture looks uniformly cloudy and slightly thickened, rather than separated.",
          "Taste and adjust the oil-to-acid ratio — a common starting point is roughly 3 parts oil to 1 part acid.",
        ],
        tip: "Mustard isn't just for flavor here — it's a natural emulsifier that helps the vinaigrette hold together longer before separating again.",
        youtube: { url: "https://www.youtube.com/watch?v=O0bQRg7ogNw", title: "Easy Vinaigrette In Minutes!", channel: "Chef Jean-Pierre" },
      },
      {
        id: "reducing-a-sauce",
        title: "Reducing a Sauce",
        steps: [
          "Simmer a sauce or liquid uncovered so steam can escape and water content evaporates.",
          "Stir occasionally, especially as it thickens, to prevent scorching on the bottom.",
          "Judge doneness by how the liquid coats the back of a spoon, not by a fixed time — every batch reduces at a different rate.",
          "Taste as you go — flavor concentrates along with texture, so seasoning that was correct at the start can become too strong by the end.",
        ],
        tip: "Salt concentrates as a sauce reduces just like everything else — season lightly at the start of a reduction and adjust again at the end, not the other way around.",
        youtube: { url: "https://www.youtube.com/watch?v=hcMQo-iJa94", title: "Steak with a Red Wine Reduction", channel: "Chef Jean-Pierre" },
      },
    ],
  },
  {
    id: "egg-techniques",
    title: "Egg Techniques",
    skills: [
      {
        id: "scrambled-eggs",
        title: "Perfect Scrambled Eggs",
        steps: [
          "Whisk eggs thoroughly with a pinch of salt until uniform in color.",
          "Cook in butter over low-medium heat, not high — low heat is what keeps scrambled eggs soft.",
          "Stir or fold constantly with a spatula, pulling curds from the edges toward the center.",
          "Remove from heat while still slightly underdone — residual heat finishes them, and they firm up more off the pan.",
        ],
        tip: "High heat is the most common mistake — it turns eggs rubbery and watery almost instantly; low and slow with constant motion is what produces soft, creamy curds.",
        youtube: { url: "https://www.youtube.com/watch?v=KaKvTA9G0i4", title: "Tips For Making The Perfect Scrambled Eggs", channel: "Chef Jean-Pierre" },
      },
      {
        id: "poaching-egg",
        title: "Poaching an Egg",
        steps: [
          "Bring a pot of water to a bare simmer and add a splash of vinegar to help the whites set faster.",
          "Crack the egg into a small cup or ramekin first, not directly into the pot.",
          "Create a gentle whirlpool in the water with a spoon, then slide the egg into the center.",
          "Cook for about 3 minutes for a runny yolk, then lift out with a slotted spoon and drain on a towel.",
        ],
        tip: "Cracking the egg into a cup first (rather than directly into the pot) lets you catch any shell fragments and control exactly where and how gently it enters the water.",
        youtube: { url: "https://www.youtube.com/watch?v=XjxDGssvfIg", title: "Carla Makes Poached Eggs", channel: "Bon Appétit" },
      },
      {
        id: "french-omelette",
        title: "The French Omelette",
        steps: [
          "Whisk eggs very well until completely smooth and uniform.",
          "Cook in butter over medium-low heat, stirring constantly with a fork or spatula while shaking the pan, to form small, even curds without browning.",
          "Once mostly set but still slightly wet on top, stop stirring and let it finish for a few seconds.",
          "Tilt the pan and roll the omelette out onto a plate, folding it into a smooth log shape as it goes — no color, no fold lines showing brown.",
        ],
        tip: "A French omelette should have zero browning — if you're seeing golden or brown spots, the heat is too high; French style prizes a pale, tender, almost custard-like interior.",
        youtube: { url: "https://www.youtube.com/watch?v=viUNdDENnDU", title: "Standard Omelet vs. Classic French Omelet", channel: "Jacques Pépin Foundation" },
      },
      {
        id: "hollandaise",
        title: "Hollandaise Sauce",
        steps: [
          "Whisk egg yolks with a splash of water or lemon juice in a bowl set over a pot of barely simmering water (double boiler) until pale and slightly thickened.",
          "Remove from heat and slowly drizzle in warm melted butter while whisking constantly, building an emulsion the same way as a vinaigrette.",
          "Season with lemon juice, salt, and a pinch of cayenne.",
          "Keep warm but not hot — hollandaise breaks (separates) if it gets too hot or sits too long.",
        ],
        tip: "If the sauce breaks (looks greasy and separated), whisk a teaspoon of warm water into a fresh yolk and slowly whisk the broken sauce back into it — this usually rescues it.",
        youtube: { url: "https://www.youtube.com/watch?v=NEhmNhrYp78", title: "3 Minute Hollandaise, Eggs Benedict", channel: "Chef Jean-Pierre" },
      },
    ],
  },
  {
    id: "protein-techniques",
    title: "Protein Techniques",
    skills: [
      {
        id: "proper-sear",
        title: "Achieving a Proper Sear",
        steps: [
          "Pat the surface completely dry and season just before cooking.",
          "Use a hot, heavy pan and enough high-smoke-point oil to coat the bottom.",
          "Lay the food away from you and leave it completely undisturbed until it releases naturally with a deep brown crust.",
          "Flip once and repeat, then finish to temperature.",
        ],
        tip: "A wet surface steams instead of searing — the drier the surface going into the pan, the faster and deeper the browning (Maillard reaction) will be.",
        youtube: { url: "https://www.youtube.com/watch?v=45Ch3PMDe30", title: "The Best Way to Sear a Steak (Hint: We Use a Secret Ingredient)", channel: "America's Test Kitchen" },
      },
      {
        id: "doneness-temps",
        title: "Doneness Temperatures & Thermometer Use",
        steps: [
          "Insert an instant-read thermometer into the thickest part of the food, avoiding bone, which conducts heat differently.",
          "Common targets: beef/lamb medium-rare ~130-135°F (54-57°C), poultry 165°F (74°C), pork ~145°F (63°C) with a rest, fish ~130-140°F (54-60°C) depending on type.",
          "Remember carryover cooking — food continues to rise several degrees after leaving heat, so pull it a few degrees before your final target.",
        ],
        tip: "A thermometer removes the guesswork entirely — cutting into meat to 'check' lets valuable juices escape and still doesn't tell you the temperature at the very center.",
        youtube: { url: "https://www.youtube.com/watch?v=p5SVK7m2M3s", title: "How to Take Meat Temperatures", channel: "Food Network" },
      },
      {
        id: "resting-meat",
        title: "Resting Meat",
        steps: [
          "After cooking, transfer meat to a plate or board and let it sit, loosely tented with foil, before cutting.",
          "Rest roughly 5 minutes for a steak-sized piece, up to 15-20+ minutes for a large roast.",
          "Resist cutting in early — the goal is to let juices redistribute through the meat rather than spill out onto the board.",
        ],
        tip: "Cutting into meat straight off the heat loses a visibly larger amount of juice than cutting after a rest — the muscle fibers relax and reabsorb liquid as the temperature evens out.",
        youtube: { url: "https://www.youtube.com/watch?v=9Nxst8lhwNM", title: "Does Resting Meat Matter?", channel: "America's Test Kitchen (Techniquely with Lan Lam)" },
      },
      {
        id: "brining",
        title: "Brining",
        steps: [
          "Dissolve salt (and often sugar) into water to make a brine — a common ratio is about 1 cup kosher salt per gallon of water.",
          "Submerge the meat fully, refrigerated, for a time appropriate to its size (a chicken breast might take an hour; a turkey needs many hours to overnight).",
          "Rinse and pat dry thoroughly before cooking to avoid an overly salty surface.",
        ],
        tip: "Brining works by osmosis and protein changes that help meat hold onto more moisture during cooking — it's most valuable for lean cuts (chicken breast, pork loin, turkey) that dry out easily.",
        youtube: { url: "https://www.youtube.com/watch?v=6VhD5QyDEh4", title: "3 Salting Methods for Better-Tasting Meats", channel: "America's Test Kitchen (Techniquely with Lan Lam)" },
      },
      {
        id: "marinating-safely",
        title: "Marinating Safely",
        steps: [
          "Combine an acid or enzyme (citrus, vinegar, yogurt, pineapple), oil, and seasonings in a non-reactive container or zip-top bag.",
          "Submerge the food and refrigerate — never marinate at room temperature.",
          "Marinate for an appropriate time: delicate proteins like fish or shrimp for 15-30 minutes, sturdier meats for a few hours to overnight (too long in a strong acid can turn texture mushy).",
          "Discard any marinade that touched raw meat — never reuse it as a sauce unless you boil it thoroughly first.",
        ],
        tip: "Marinades penetrate only a few millimeters no matter how long you wait — beyond a certain point you're mostly changing surface texture, not deeply 'flavoring' the inside of a thick cut.",
        youtube: { url: "https://www.youtube.com/watch?v=cIZi1SO22wo", title: "Get Better Tasting Meat: 5 Keys to Marinating", channel: "America's Test Kitchen (Techniquely with Lan Lam)" },
      },
    ],
  },
  {
    id: "baking-pastry",
    title: "Baking & Pastry Basics",
    skills: [
      {
        id: "creaming-method",
        title: "The Creaming Method",
        steps: [
          "Beat softened (not melted) butter with sugar on medium speed until pale, light, and fluffy — a few minutes, not a few seconds.",
          "Add eggs one at a time, beating well after each addition so they fully incorporate.",
          "Alternate adding dry ingredients and any liquid in a few additions, mixing just until combined.",
        ],
        tip: "The 'fluffy' stage isn't cosmetic — beating air into the butter-sugar mixture creates tiny pockets that expand in the oven and give cookies and cakes their structure and lift.",
        youtube: { url: "https://www.youtube.com/watch?v=ThJi3p2As6M", title: "How to Cream Butter and Sugar", channel: "Food Network" },
      },
      {
        id: "bread-dough-kneading",
        title: "Basic Bread Dough & Kneading",
        steps: [
          "Combine flour, water, yeast, salt, and any enrichments into a shaggy dough.",
          "Turn onto a lightly floured surface and knead by pushing the dough away with the heel of your hand, folding it back over itself, and rotating a quarter turn, repeating rhythmically.",
          "Continue for about 8-10 minutes by hand until the dough turns smooth, elastic, and springs back when poked.",
          "Let rise in an oiled, covered bowl until roughly doubled before shaping.",
        ],
        tip: "Kneading develops gluten — the protein network that traps gas bubbles from the yeast — which is why underkneaded dough produces dense, flat bread rather than an open, airy crumb.",
        youtube: { url: "https://www.youtube.com/watch?v=Jizr6LR83Kk", title: "Bread Part 1 | Basics with Babish", channel: "Binging with Babish" },
      },
      {
        id: "pie-dough",
        title: "Working with Pie Dough",
        steps: [
          "Cut very cold butter into flour and salt until the pieces are pea-sized — a food processor, pastry cutter, or your fingertips all work.",
          "Add ice water a little at a time, mixing just until the dough barely comes together — don't overwork it.",
          "Chill the dough, wrapped, for at least 30 minutes before rolling.",
          "Roll on a floured surface from the center outward, rotating the dough as you go to keep an even circle.",
        ],
        tip: "Keeping everything cold — butter, water, even the bowl — is the entire secret to flaky pie crust: those unmelted bits of butter create steam pockets in the oven that separate the dough into flaky layers.",
        youtube: { url: "https://www.youtube.com/watch?v=NLxGcFr93TM", title: "Claire Saffitz Makes Easy Pie Dough & Savory Galette", channel: "Claire Saffitz x Dessert Person" },
      },
      {
        id: "whipping-meringue",
        title: "Whipping Egg Whites to Meringue",
        steps: [
          "Start with a completely clean, grease-free bowl and whisk — any fat will prevent whites from whipping properly.",
          "Separate eggs carefully, keeping any yolk out of the whites.",
          "Beat whites on medium speed until foamy, then add sugar gradually while increasing speed.",
          "Continue to your target stage: soft peaks droop when the whisk is lifted; stiff peaks hold their shape upright.",
        ],
        tip: "A trace of egg yolk or a greasy bowl is the most common reason whites won't whip — fat disrupts the protein structure that traps air, so cleanliness matters more than technique here.",
        youtube: { url: "https://www.youtube.com/watch?v=zhuRyq7NrcA", title: "Whipping Egg Whites To Perfect Peaks", channel: "Everyday Food" },
      },
      {
        id: "tempering-chocolate",
        title: "Tempering Chocolate",
        steps: [
          "Melt about two-thirds of your chocolate gently (double boiler or short microwave bursts) to around 115°F (46°C) for dark chocolate.",
          "Remove from heat and add the remaining unmelted chocolate, stirring until it cools to around 82°F (28°C) — this 'seeds' the correct crystal structure.",
          "Gently rewarm to working temperature, around 88-90°F (31-32°C) for dark chocolate, being careful not to overshoot.",
          "Test by dabbing a small amount on parchment — properly tempered chocolate sets glossy and firm within a few minutes at room temperature.",
        ],
        tip: "Tempering is about controlling which crystal structure the cocoa butter sets into — done right, chocolate snaps cleanly and looks glossy; done wrong, it stays soft, dull, or develops a pale, streaky bloom.",
        youtube: { url: "https://www.youtube.com/watch?v=98r0Z3jeYcE", title: "How to Temper Chocolate with Martha Stewart", channel: "Martha Stewart" },
      },
    ],
  },
  {
    id: "plating-serving",
    title: "Plating & Serving",
    skills: [
      {
        id: "plating-principles",
        title: "Basic Plating Principles",
        steps: [
          "Choose a focal point and build around it rather than spreading everything evenly across the plate.",
          "Use odd numbers of items (the 'rule of odds') for a more natural, visually interesting arrangement.",
          "Leave negative space — a plate doesn't need to be filled edge to edge to look generous.",
          "Wipe the rim clean before serving; smudges and drips read as careless even if the food is great.",
        ],
        tip: "Height and contrast (in color and texture) do more for a plate's appeal than symmetry — a few tall, uneven elements usually look more appetizing than everything laid flat and evenly spaced.",
        youtube: { url: "https://www.youtube.com/watch?v=te9Vxars3MQ", title: "A Chef's Guide to Great Plating | Basic, Intermediate, Expert", channel: "Sorted Food" },
      },
      {
        id: "portion-sizing",
        title: "Portion Sizing",
        steps: [
          "Use rough per-person guides as a starting point: about 4-6 oz of protein, 1/2-1 cup of starch, and 1 cup of vegetables per main-course serving.",
          "Adjust for the number of courses — a starter or family-style spread calls for smaller individual portions than a single main course.",
          "Weigh or measure when consistency matters (e.g., cooking for a group), rather than eyeballing every plate differently.",
        ],
        tip: "These numbers are a starting point, not a rule — richness of the dish, number of courses, and who you're feeding all shift what a 'right-sized' portion actually looks like.",
        youtube: null,
      },
      {
        id: "serving-temperatures",
        title: "Correct Serving Temperatures",
        steps: [
          "Hot dishes should genuinely be hot at the table — warm plates in advance for food that cools quickly (like a seared protein).",
          "Cold dishes (salads, chilled soups, many desserts) should be served properly chilled, not lukewarm.",
          "Some items are best at room temperature (many cheeses, certain fruits) — check what's actually appropriate rather than defaulting to 'hot or cold.'",
          "Time your cooking so multiple components finish close together rather than the first dish going cold while the last one finishes.",
        ],
        tip: "A warmed plate makes a bigger difference than most home cooks expect — food loses heat fast to a cold ceramic plate, and warming plates in a low oven for a few minutes beforehand noticeably extends how long food stays hot.",
        youtube: null,
      },
      {
        id: "timing-a-meal",
        title: "Timing a Meal",
        steps: [
          "Work backward from your target serving time, listing every component and how long each takes.",
          "Identify what can be made ahead and held (sauces, sides that reheat well) versus what must be cooked à la minute (seared proteins, anything meant to be crisp).",
          "Start the longest-cooking or make-ahead items first; save fast, last-minute items (searing, plating delicate garnishes) for right before serving.",
          "Use resting time strategically — a resting protein gives you a built-in window to finish sides or plate.",
        ],
        tip: "The goal isn't finishing everything at the exact same second — it's sequencing so that things which hold well (braises, starches) rest while things that don't (seared proteins, crisp items) happen last.",
        youtube: null,
      },
    ],
  },
];

export function getAllSkills() {
  return CULINARY_CATEGORIES.flatMap((cat) =>
    cat.skills.map((skill) => ({ ...skill, categoryId: cat.id, categoryTitle: cat.title }))
  );
}
